apiVersion: harness.io/v1
kind: System
type: test-system
identifier: idpautomationsystem17718237378614572
name: idp-automation-system-1771823737861-4572
owner: user:account/idp-release-automation-ui@harnessioprivate.testinator.com
spec:
  lifecycle: ''
metadata:
  description: Test IDP System CRUD Operation
  tags:
  - java
