apiVersion: harness.io/v1
kind: customkindfordemo
type: service
identifier: TestCustomEntityKindGitX
name: Cluster Config GitX
owner: group:account/AI_Test_Automation
orgIdentifier: default
projectIdentifier: IDP
spec:
  lifecycle: experimental
metadata:
  description: Test
  tags:
  - java
